# Initialising the branching process
library(data.table)

#' @param num.initial.cases number of individuals in the 0th generation
#' @param prop.asym proportion of asymptomatic individuals in the unvaccinated subpopulation
#' @param prob_vacc proportion of vaccinated individuals in the branching process 
#' @param delayfn_ parameters of the distribution of behvioral delays
#' @param inf_ parameters of the distribution of generation times
#' @param incfn parameters of the distribution of incubation periods
#' @param incfn_vaccinated
#' @param quarantine parameter that is not used
#' @param disp. dispersion parameters of the distribution of the number of secondary cases
#' @param r0subclin.vaccinated mean number of secondary cases generated by an asymptomatic vaccinated individual
#' @param r0subclin mean number of secondary cases generated by an asymptomatic unvaccianted case
#' @param r0community.vaccinated mean number of secondary cases generated by a symptomatic vaccinated individual
#' @param r0community mean number of secondary cases generated by a symptomatic unvaccinated case

outbreak_setup <- function(num.initial.cases,
                           prop.asym,
                           prob_vacc,

                           delayfn_subclin,
                           delayfn_vaccinated_subclin,
                           delayfn_sympt,
                           delayfn_vaccinated_sympt,

                           inf_shape,
                           inf_rate,
                           inf_shift,
                           inf_shape_vaccinated,
                           inf_rate_vaccinated,
                           inf_shift_vaccinated,

                           incfn,
                           incfn_vaccinated,

                           quarantine,

                           disp.subclin.vaccinated,
                           disp.subclin,
                           disp.com.vaccinated,
                           disp.com,
                           r0subclin.vaccinated,
                           r0subclin,
                           r0community.vaccinated,
                           r0community
                           ) {

vect_isTRUE <- function(x) {
purrr::map_lgl(x, isTRUE)
}

case_data <- data.table(exposure = runif(num.initial.cases, 0, 4.6),
                      infector = 0,
                      missed = TRUE,
                      new_cases = NA,
                      vaccinated = purrr::rbernoulli(num.initial.cases, prob_vacc*(1-as.numeric(prob_immune(1)[[2]]))/(prob_vacc*(1-as.numeric(prob_immune(1)[[2]])) + 1 - prob_vacc)),
                      removed = FALSE,
                      first_test = NA,
                      time_first_test = NA,
                      onset = NA,
                      times_infection = NA
)

case_data <- case_data[, asym := ifelse(vect_isTRUE(vaccinated),
                                      purrr::rbernoulli(nrow(case_data[vect_isTRUE(vaccinated)]), as.numeric(prop.asym.vaccinated(nrow(case_data[vect_isTRUE(vaccinated)]), prop.asym)[[1]])),
                                      purrr::rbernoulli(nrow(case_data[!vect_isTRUE(vaccinated)]), prop.asym))
                     ]

num.initial.vaccinated <- nrow(case_data[vaccinated == TRUE])

case_data$onset[vect_isTRUE(case_data$vaccinated)] <- incfn_vaccinated(n = num.initial.vaccinated)
case_data$onset[!vect_isTRUE(case_data$vaccinated)] <- incfn(n = num.initial.cases - num.initial.vaccinated)

case_data <- case_data[, isolated_time := Inf][, isolated := FALSE]

case_data <- case_data %>% mutate(isolated_exit_time = NA) %>%
  mutate(isolated = FALSE)

temporary <- purrr::map2_dbl(
  ifelse(vect_isTRUE(case_data$vaccinated),
         ifelse(vect_isTRUE(case_data$asym),
                disp.subclin.vaccinated,
                disp.com.vaccinated),
         ifelse(vect_isTRUE(case_data$asym),
                disp.subclin,
                disp.com)),

  ifelse(vect_isTRUE(case_data$vaccinated),
         ifelse(vect_isTRUE(case_data$asym),
                r0subclin.vaccinated,
                r0community.vaccinated),
         ifelse(vect_isTRUE(case_data$asym),
                r0subclin,
                r0community)),
  ~ rnbinom(1, size = .x, mu = .y))
case_data$new_cases <- temporary

case_data$times_infection[vect_isTRUE(case_data$vaccinated)] <- inf_fn(case_data$new_cases[vect_isTRUE(case_data$vaccinated)], inf_shape_vaccinated, inf_rate_vaccinated, inf_shift_vaccinated)
case_data$times_infection[!vect_isTRUE(case_data$vaccinated)] <- inf_fn(case_data$new_cases[vect_isTRUE(!case_data$vaccinated)], inf_shape, inf_rate, inf_shift)

case_data <- case_data[, t_1 := NA]
case_data <- case_data[, t_2 := NA]
nn <- 4
schrom_sensitivity <- 0.98
for (i in 1:nrow(case_data)){
  if(!is.na(case_data$times_infection[i]) & length(case_data$times_infection[i]) >= nn){
    case_data$t_1[i] <- min(case_data$times_infection)
    case_data$t_2[i] <- max(case_data$times_infection)
  }
  if(length(case_data$times_infection[i]) < nn | is.na(case_data$times_infection[i])){
    if (length(case_data$times_infection[i]) < 1 | is.na(case_data$times_infection[i])){
      bla <- inf_fn(nn, 
                    inf_shape, 
                    inf_rate, 
                    inf_shift)
    } else {
      bla <- inf_fn(nn - length(case_data$times_infection[i]), 
                    inf_shape, 
                    inf_rate, 
                    inf_shift)
      bla <- c(case_data$times_infection[i], bla)
    }
    
    case_data$t_1[i] <- min(unlist(bla))
    case_data$t_2[i] <- max(unlist(bla))
  }
}
sensitivity_individual <- function(time, t_1, t_2){
  for(i in 1: length(time)){
    time[i] <- time[i] + case_data$onset[i]
  }
  out <- c()
  for(i in 1: length(time)){
    if(is.na(time[i])){
      out[i] <- 0
    }
    if(!is.na(time[i])){
      if (time[i] < (t_2[i]-t_1[i])/2 + t_1[i]){ ## b is the half-height position, a is the steepness
        if (t_1[i]<=1){
          if (time[i] < t_1[i]){
            out[i] <- pracma::sigmoid(time[i], a = 15, b = t_1[i])*schrom_sensitivity
          }
          if (time[i] >= t_1[i] & (time[i] < (t_2[i]-t_1[i])/2 + t_1[i])) {
            out[i] <- pracma::sigmoid(time[i], a = 4.7, b = t_1[i])*schrom_sensitivity
          }
        } else {
          out[i] <- pracma::sigmoid(time[i], a = 4.7, b = t_1[i])*schrom_sensitivity
        }
      }
      if (time[i] >= (t_2[i]-t_1[i])/2 + t_1[i]){
        out[i] <- pracma::sigmoid(time[i], a = -4.7, b = t_2[i])*schrom_sensitivity
      }
    }
  }
  return(out)
}

case_data <- case_data %>% mutate(first_test = ifelse(case_data$asym==FALSE,
                                                      purrr::rbernoulli(nrow(case_data), sensitivity_individual(rep(0, nrow(case_data)), t_1, t_2)),
                                                      NA))

case_data <- case_data %>% mutate(first_pos = ifelse(vect_isTRUE(first_test),
                                                     TRUE,
                                                     NA))

case_data <- case_data %>% mutate(time_first_test = ifelse(case_data$first_test == TRUE,
                                                           onset,
                                                           NA))

case_data <- as.data.table(case_data)
case_data <- case_data[, caseid := 1:(num.initial.cases)]
case_data$timeexp <- case_data$exposure

case_data[, c("t_1","t_2") := NULL]

return(case_data)
}

