# run several realisations of the branching process and save it in a data.table

#' @param num.initial.cases number of individuals in the 0th generation
#' @param prop.asym proportion of asymptomatic individuals in the unvaccinated subpopulation
#' @param prob_vacc proportion of vaccinated individuals in the branching process 
#' @param delayfn_ parameters of the distribution of behavioral delays
#' @param inf_ parameters of the distribution of generation times
#' @param incfn parameters of the distribution of incubation periods
#' @param incfn_vaccinated
#' @param quarantine parameter that is not used
#' @param disp. dispersion parameters of the distribution of the number of secondary cases
#' @param r0subclin.vaccinated mean number of secondary cases generated by an asymptomatic vaccinated individual
#' @param r0subclin mean number of secondary cases generated by an asymptomatic unvaccianted case
#' @param r0community.vaccinated mean number of secondary cases generated by a symptomatic vaccinated individual
#' @param r0community mean number of secondary cases generated by a symptomatic unvaccinated case
#' @param prop.ascertain probability that an offspring will be traced by its infector if the infector traces its contacts
#' @param test_delay_antigenic delay between test sampling and test result for antigenic tests
#' @param scenario which protocol
#' @param awareness probability that an individual tests a second time if negative but symptomatic
#' @param number_daily_tests maximum number of daily performed tests for individuals who are negative and symptomatic
#' @param comply probability of repeating a test more than twice if negative but symptomatic
#' @param test_compliance_sympt compliance to getting tested if recommended to do so by health authorities, if symptomatic
#' @param test_compliance_asymptcompliance to getting tested if recommended to do so by health authorities, if asymptomatic
#' @param probability_full_iso_sympt compliance to isolation if symptomatic and if recommended by authorities to do so
#' @param probability_full_iso_asympt compliance to isolation if asymptomatic and if recommended by authorities to do so

scenario_sim <- function(n.sim = NULL,
                         num.initial.cases = NULL,
                         prop.ascertain = NULL,
                         prop.asym = NULL,
                         cap_max_days = NULL,
                         prob_vacc = NULL,

                         delay_scale = NULL,
                         delay_shape_sympt = NULL,
                         delay_shape_vaccinated_sympt = NULL,
                         delay_shape_subclin = NULL,
                         delay_shape_vaccinated_subclin = NULL,

                         inc_meanlog = NULL,
                         inc_sdlog = NULL,
                         inc_sdlog_vacc = NULL,
                         inc_meanlog_vacc = NULL,

                         r0isolated = NULL,
                         r0community = NULL,
                         disp.com = NULL,
                         disp.com.vaccinated = NULL,
                         r0subclin = NULL,
                         disp.subclin = NULL,
                         disp.subclin.vaccinated = NULL,
                         vaccine_transmission_reduction = NULL,

                         inf_shape = NULL,
                         inf_shift = NULL,
                         inf_rate = NULL,
                         inf_shape_vaccinated = NULL,
                         inf_shift_vaccinated = NULL,
                         inf_rate_vaccinated = NULL,

                         quarantine = NULL,

                         test_delay_antigenic = NULL,
                         scenario = NULL,
                         awareness = NULL,
                         number_daily_tests = NULL,
                         comply = NULL,
                         test_compliance_sympt = NULL,
                         test_compliance_asympt = NULL,
                         probability_full_iso_sympt = NULL,
                         probability_full_iso_asympt = NULL
                         ) {


  # In input, r0community is the intrinsic transmissibility of the historical strain and r0subclin is the relative infectiousness of asymptomatic compared to symptomatic individuals
  r0community <- 2*1.45*r0community/(prop.asym*r0subclin + 1 - prop.asym)
  r0subclin <- r0subclin*r0community

  r0community.vaccinated <- r0community*(1-vaccine_transmission_reduction)
  r0subclin.vaccinated <- r0subclin*(1-vaccine_transmission_reduction)

  res <- purrr::map(.x = 1:n.sim, ~ outbreak_model(num.initial.cases = num.initial.cases,
                                                   run = .x,
                                                   prop.ascertain = prop.ascertain,
                                                   prop.asym = prop.asym,
                                                   cap_max_days = cap_max_days,
                                                   prob_vacc = prob_vacc,

                                                   delay_scale = delay_scale,
                                                   delay_shape_sympt = delay_shape_sympt,
                                                   delay_shape_vaccinated_sympt = delay_shape_vaccinated_sympt,
                                                   delay_shape_subclin = delay_shape_subclin,
                                                   delay_shape_vaccinated_subclin = delay_shape_vaccinated_subclin,

                                                   inc_meanlog = inc_meanlog,
                                                   inc_sdlog = inc_sdlog,
                                                   inc_sdlog_vacc = inc_sdlog_vacc,
                                                   inc_meanlog_vacc = inc_meanlog_vacc,

                                                   r0isolated = r0isolated,
                                                   r0community = r0community,
                                                   r0community.vaccinated = r0community.vaccinated,
                                                   disp.com = disp.com,
                                                   disp.com.vaccinated = disp.com.vaccinated,
                                                   r0subclin = r0subclin,
                                                   r0subclin.vaccinated = r0subclin.vaccinated,
                                                   disp.subclin = disp.subclin,
                                                   disp.subclin.vaccinated = disp.subclin.vaccinated,

                                                   inf_shape = inf_shape,
                                                   inf_rate = inf_rate,
                                                   inf_shift = inf_shift,
                                                   inf_shape_vaccinated = inf_shape_vaccinated,
                                                   inf_rate_vaccinated = inf_rate_vaccinated,
                                                   inf_shift_vaccinated = inf_shift_vaccinated,
                                                   quarantine = quarantine,
                                                   test_delay_antigenic = test_delay_antigenic,
                                                   scenario = scenario,
                                                   awareness = awareness,
                                                   number_daily_tests = number_daily_tests,
                                                   comply = comply,
                                                   test_compliance_sympt = test_compliance_sympt,
                                                   test_compliance_asympt = test_compliance_asympt,
                                                   probability_full_iso_sympt = probability_full_iso_sympt,
                                                   probability_full_iso_asympt = probability_full_iso_asympt
                                             ))

  # bind output together and add simulation index
  res <- data.table::rbindlist(res)
  res[, sim := rep(1:n.sim, rep(1, n.sim))]
  
  return(res)
}


